-- Seed data for Pretoria Hidden Gems
INSERT INTO places (name, slug, category, subcategory, area, suburb, description, why_go, best_for, price_type, min_price, max_price, address, latitude, longitude, website_url, phone, opening_hours, hero_image, gallery_images, tags, is_featured, rating)
VALUES
(
  'Faerie Glen Nature Reserve',
  'faerie-glen-nature-reserve',
  'Outdoor & Nature',
  'Hiking',
  'Pretoria East',
  'Faerie Glen',
  'A beautiful escape in the heart of the city with hiking trails and scenic views.',
  'It is one of the few places in Pretoria where you can truly feel like you are out in the wild without leaving the city.',
  'Morning hikes, bird watching, and photography.',
  'Free',
  0,
  0,
  'January Masilela Dr, Faerie Glen, Pretoria, 0081',
  -25.7744,
  28.2919,
  'https://www.tshwane.gov.za',
  '012 358 1510',
  '{"Monday - Sunday": "06:00 - 18:00"}',
  'https://picsum.photos/seed/faerie/1200/800',
  '{"https://picsum.photos/seed/faerie1/800/600", "https://picsum.photos/seed/faerie2/800/600"}',
  '{"Hiking", "Nature", "Dog Friendly"}',
  true,
  4.8
),
(
  'Rietvlei Nature Reserve',
  'rietvlei-nature-reserve',
  'Outdoor & Nature',
  'Wildlife',
  'Pretoria South',
  'Rietvalleirand',
  'One of the worlds largest urban nature reserves, home to rhino, buffalo, and cheetah.',
  'You can see the Big Five (almost) right on your doorstep in a peaceful, well-maintained environment.',
  'Game drives, fishing, and bird hides.',
  'Under R100',
  65,
  65,
  '14 Game Reserve Ave, Rietvalleirand, Pretoria, 0181',
  -25.8833,
  28.2667,
  'https://www.tshwane.gov.za',
  '012 358 1701',
  '{"Monday - Sunday": "06:00 - 18:00"}',
  'https://picsum.photos/seed/rietvlei/1200/800',
  '{"https://picsum.photos/seed/rietvlei1/800/600"}',
  '{"Wildlife", "Safari", "Cheetah"}',
  true,
  4.7
),
(
  'Hazel Food Market',
  'hazel-food-market',
  'Markets',
  'Food',
  'Pretoria East',
  'Menlo Park',
  'A vibrant Saturday morning market featuring artisanal food, fresh produce, and local crafts.',
  'The atmosphere is unmatched, and the variety of international street food is incredible.',
  'Saturday brunch, family outings, and foodies.',
  'Under R100',
  0,
  100,
  '378 Queen''s Cres, Lynnwood, Pretoria, 0081',
  -25.7689,
  28.2567,
  'https://www.hazelfoodmarket.co.za',
  '078 593 7716',
  '{"Saturday": "08:00 - 14:00"}',
  'https://picsum.photos/seed/hazel/1200/800',
  '{"https://picsum.photos/seed/hazel1/800/600"}',
  '{"Market", "Foodie", "Saturday"}',
  true,
  4.9
),
(
  'Market @ The Sheds',
  'market-the-sheds',
  'Markets',
  'Culture',
  'Pretoria Central',
  'CBD',
  'An inner-city market that celebrates art, music, and the diverse culture of Pretoria.',
  'It is the coolest place to experience the urban vibe of Pretoria with live jazz and local fashion.',
  'Live music, art lovers, and social butterflies.',
  'Under R100',
  50,
  50,
  '381 Helen Joseph St, Pretoria Central, Pretoria, 0002',
  -25.7461,
  28.1931,
  'https://www.marketatthesheds.co.za',
  '082 854 6854',
  '{"Last Saturday of month": "11:00 - 20:00"}',
  'https://picsum.photos/seed/sheds/1200/800',
  '{"https://picsum.photos/seed/sheds1/800/600"}',
  '{"Jazz", "Art", "Inner City"}',
  false,
  4.6
),
(
  'Rosemary Hill Farm',
  'rosemary-hill-farm',
  'Outdoor & Nature',
  'Farm',
  'Pretoria East',
  'Donkerhoek',
  'A beautiful organic farm with mountain bike trails, a coffee shop, and stunning gardens.',
  'The trails are world-class, and the farm-to-table food is fresh and delicious.',
  'Mountain biking, trail running, and afternoon tea.',
  'Under R100',
  40,
  80,
  'R964, Pretoria, 0001',
  -25.7917,
  28.4417,
  'https://www.rosemaryhill.co.za',
  '012 802 0052',
  '{"Monday - Sunday": "07:00 - 17:00"}',
  'https://picsum.photos/seed/rosemary/1200/800',
  '{"https://picsum.photos/seed/rosemary1/800/600"}',
  '{"MTB", "Farm", "Trails"}',
  true,
  4.8
),
(
  'Capital Craft Beer Academy',
  'capital-craft-beer-academy',
  'Restaurants',
  'Pub',
  'Pretoria East',
  'Menlo Park',
  'The ultimate destination for craft beer lovers, featuring a massive selection and great burgers.',
  'They have one of the largest craft beer selections in the country and a great vibe.',
  'Beer tasting, burgers, and hanging out with friends.',
  'Under R250',
  100,
  250,
  'Shop 20, Greenlyn Village Centre, Menlo Park, Pretoria, 0081',
  -25.7694,
  28.2561,
  'https://www.capitalcraft.co.za',
  '012 424 8601',
  '{"Monday - Sunday": "10:00 - 00:00"}',
  'https://picsum.photos/seed/beer/1200/800',
  '{"https://picsum.photos/seed/beer1/800/600"}',
  '{"Craft Beer", "Burgers", "Nightlife"}',
  false,
  4.7
),
(
  'Afroboer',
  'afroboer',
  'Coffee Shops',
  'Bakery',
  'Pretoria East',
  'Die Wilgers',
  'A quirky bakery and cafe with a beautiful garden and incredible breakfast.',
  'The food is creative and soulful, and the garden setting is peaceful and inviting.',
  'Breakfast, coffee dates, and cake.',
  'Under R250',
  80,
  200,
  '1 Meerlust Rd, Equestria, Pretoria, 0184',
  -25.7633,
  28.3167,
  'https://www.afroboer.co.za',
  '012 807 3099',
  '{"Monday - Saturday": "07:00 - 17:00"}',
  'https://picsum.photos/seed/afroboer/1200/800',
  '{"https://picsum.photos/seed/afroboer1/800/600"}',
  '{"Bakery", "Garden", "Breakfast"}',
  true,
  4.8
),
(
  'The Big Red Barn',
  'the-big-red-barn',
  'Fun Activities',
  'Adventure',
  'Irene',
  'Olifantsfontein',
  'An adventure park with tree-top climbing, cycling trails, and a great restaurant.',
  'It is a fantastic place for kids and adults to get active in a beautiful forest setting.',
  'Kids parties, cycling, and family fun.',
  'Under R250',
  50,
  250,
  '7 Nelson Rd, Olifantsfontein, 1666',
  -25.9250,
  28.2333,
  'https://www.thebigredbarn.co.za',
  '072 617 7667',
  '{"Monday - Sunday": "08:00 - 17:00"}',
  'https://picsum.photos/seed/barn/1200/800',
  '{"https://picsum.photos/seed/barn1/800/600"}',
  '{"Adventure", "Kids", "Forest"}',
  false,
  4.5
),
(
  'Acrobranch Centurion',
  'acrobranch-centurion',
  'Fun Activities',
  'Adventure',
  'Centurion',
  'Irene',
  'A world-class zip-lining and obstacle course set in the trees of the Big Red Barn.',
  'It is a thrilling way to experience the forest from above with courses for all ages.',
  'Adrenaline junkies, kids, and team building.',
  'Under R250',
  150,
  280,
  '7 Nelson Rd, Olifantsfontein, 1666',
  -25.9250,
  28.2333,
  'https://acrobranch.co.za',
  '086 999 0369',
  '{"Wednesday - Sunday": "09:00 - 17:00"}',
  'https://picsum.photos/seed/acro/1200/800',
  '{"https://picsum.photos/seed/acro1/800/600"}',
  '{"Zipline", "Adventure", "Outdoors"}',
  false,
  4.6
),
(
  'Wonderboom Nature Reserve',
  'wonderboom-nature-reserve',
  'Outdoor & Nature',
  'History',
  'Pretoria North',
  'Wonderboom',
  'Home to a 1,000-year-old wild fig tree and ancient stone age sites.',
  'The massive fig tree is a natural wonder, and the hike to the fort offers great views.',
  'History buffs, nature walks, and picnics.',
  'Free',
  35,
  35,
  'Wonderboom, Pretoria, 0182',
  -25.6833,
  28.1833,
  'https://www.tshwane.gov.za',
  '012 358 1792',
  '{"Monday - Sunday": "07:00 - 18:00"}',
  'https://picsum.photos/seed/wonder/1200/800',
  '{"https://picsum.photos/seed/wonder1/800/600"}',
  '{"History", "Tree", "Picnic"}',
  false,
  4.4
);
